### ISSUE TITLE
Verify CLI step fails without manual intervention

### ISSUE THREAD

**Issue by nicobrevin** [karlmdavis/ansible-jenkins2#11]
I found I had to manually disable security to get the cli to work, and a small amount of research couldn't turn up why the cli would work over http without securtiy being disabled - neither the -i or -auth options seem to be passed to the calls to jenkins-cli.

It gave an error of 'ERROR: anonymous is missing the Overall/Read permission'

So I manually switched security off, ran the role again, and it worked.  

PS Thanks for the role!

**Comment by pheanex** [comment]
So just to clarify: You were able to reproduce the error?

**Comment by nicobrevin** [comment]
Yeah, I was - a fresh install on ubuntu 16.04 has the problem

jenkins version 2.68

**Comment by nicobrevin** [comment]
I'm trying again now, I'll paste the play output once it completes

**Comment by nicobrevin** [comment]
And now it works...  Is there anything beyond /var/lib/jenkins that I should clear out to re-test? (I can't rebuild the host right now, but can tomorrow )

**Comment by pheanex** [comment]
Can you maybe add a link to the commits/PR?
I guess /var/lib/jenkins is the most important part/path

**Comment by nicobrevin** [comment]
I'm going to close this, because it's gone away - something was up, but I can't repeat it any more.  Thanks for your attention.
