### ISSUE TITLE
Support for RHEL/CentOS 7

### ISSUE THREAD

**Issue by sahilm** [karlmdavis/ansible-jenkins2#3]
Hello - Thanks for creating and open sourcing this role. Is there any interest in supporting RHEL/CentOS 7? I can take a stab at working on it.

**Comment by karlmdavis** [comment]
Absolutely! Just as long as the tests are updated to cover it.

**Comment by sahilm** [comment]
Great. I'll send a PR soon.

**Comment by sahilm** [comment]
After surveying the landscape I've decided to go with Docker for Jenkins. Thanks for the support.
